FROM centos:centos7.7.1908

USER root
WORKDIR /

RUN yum install -y epel-release && \
    yum install -y \
		bzip2-devel \
		cmake3 \
		file \
		gcc-c++ \
		gcc-gfortran \
		git \
		subversion \
		make \
		mysql-devel \
		python \
		python-devel \
		protobuf-c-devel \
		scons \
		sudo \
		czmq \
		tree \
		wget \
		which \
		expat-devel \
		libX11-devel \
		libXt-devel \
		libXmu-devel \
		libXrender-devel \
		libXpm-devel \
		libXft-devel \
		xerces-c-devel \
		xkeyboard-config \
	&& ln -s /usr/bin/cmake3 /usr/local/bin/cmake \
	&& rm -rf /var/cache/yum

RUN git clone https://github.com/JeffersonLab/gluex_install
RUN gluex_install/gluex_prereqs_centos_7.sh
ENV NTHREADS 4
RUN gluex_install/gluex_install.sh
