

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

export BUILD_SCRIPTS=/group/halld/Software/build_scripts
export JANA_HOME=/scratch/nbrei/jana_home
export GLUEX_TOP=/group/halld/Software/builds/Linux_CentOS7-x86_64-gcc4.8.5-cntr

source $BUILD_SCRIPTS/gluex_env_boot_jlab.sh
